services:
  mongodb:
    image: mongo:latest
    container_name: 'mongo-metavest'
    hostname: mongo-metavest
    restart: unless-stopped
    volumes:
      - mongo-metavest-data:/data/db
      - mongo-metavest-log:/var/log/mongodb
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: metavest
      MONGO_INITDB_DATABASE: metavest
    ports:
      - '27017:27017'
    networks:
      - mongo_metavest_network
    healthcheck:
      test: mongosh --eval 'db.adminCommand("ping")' mongodb://root:metavest@localhost:27017/admin
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-metavest-data:
    driver: local
  mongo-metavest-log:
    driver: local

networks:
  mongo_metavest_network:
    driver: bridge