services:
  mongodb:
    image: mongo:latest
    container_name: 'mongo-bookit'
    hostname: mongo-bookit
    restart: unless-stopped
    volumes:
      - mongo-bookit-data:/data/db
      - mongo-bookit-log:/var/log/mongodb
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bookit2025
      MONGO_INITDB_DATABASE: bookit
    ports:
      - '27017:27017'
    networks:
      - mongo_bookit_network
    healthcheck:
      test: mongosh --eval 'db.adminCommand("ping")' mongodb://root:bookit2025@localhost:27017/admin
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-bookit-data:
    driver: local
  mongo-bookit-log:
    driver: local

networks:
  mongo_bookit_network:
    driver: bridge